name: faded
description: Client did not pay? Add opacity to UI components and decrease it every day until their app completely fades away. Set a due date and customize the number of days you offer them until the app is fully vanished.
version: 1.1.0
repository: https://github.com/krishnakumarcn/faded

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null

