name: faded
description: Client did not pay? Add decreasing opacity to UI components until their app fades away. Set a due date, and no. of days you offer them until the app is fully vanished.
version: 1.1.1
repository: https://github.com/krishnakumarcn/faded

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null

